[[main]]
  name = 'About'
  pageRef = '/about'
  weight = 10

[[main]]
  name = 'FAQ'
  pageRef = '/faq'
  weight = 20

[[main]]
  name = 'Code of Conduct'
  pageRef = '/codeofconduct'
  weight = 30

[[main]]
  name = 'Events'
  pageRef = '/events'
  weight = 40


[[main]]
  name = 'Sponsors'
  pageRef = '/sponsors'
  weight = 50

[[main]]
  name = 'Contact'
  pageRef = '/contact'
  weight = 60

